services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  db-initializer:
    image: postgres:15-alpine
    container_name: db-initializer
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./schema_analytics.sql:/migrations/schema_analytics.sql:ro
    entrypoint: ["/bin/sh", "-lc"]
    command: >
      until pg_isready -h postgres-db -U app_user -d appdb; do
        echo "Waiting for postgres-db...";
        sleep 2;
      done;
      psql -h postgres-db -U app_user -d appdb -f /migrations/schema_analytics.sql
    restart: "no"

  redis-queue:
    image: redis:7-alpine
    container_name: redis-queue
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
